### ISSUE TITLE
Error when installing FinBERT on local environment 

### ISSUE THREAD

**Issue by yasmineChelly-95** [TurkuNLP/FinBERT#6]
Hi, I have been working with FinBERT on colab and it works perfectly. However when I tried to work on my local environment (pycharm) I got this error when installing 

**ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from finbert-embedding)
ERROR: No matching distribution found for torch==1.1.0**

and I got the same error when I tried to downgrade torch to the 1.1.0 version

Any thoughts about what might be the reason for this ?  thanks

**Comment by haamis** [comment]
Hi,

The package `finbert-embedding` seems to be for the financial BERT, not the Finnish BERT (this repo).

However, in this case I would try updating pip first (assuming you are using it).

**Comment by yasmineChelly-95** [comment]
> Hi,
> 
> The package `finbert-embedding` seems to be for the financial BERT, not the Finnish BERT (this repo).
> 
> However, in this case I would try updating pip first (assuming you are using it).
Hi, thank you for replying. you are right I did confuse the two packages. my bad.
