### ISSUE TITLE
Preprocessing code

### ISSUE THREAD

**Issue by R4ZZ3** [TurkuNLP/FinBERT#7]
Hi,

I saw that in your paper you had done some extensive cleaning but repo is missing preprocessing code.
Could you add it to this repo, thanks in advance :)

**Comment by ogencoglu** [comment]
+1

**Comment by spyysalo** [comment]
Thanks for noting this! Linked the repo with tools in c718e6e599c60a73cb49bc9cb0c5468736783870. Apologies for the lack of documentation.
